### ISSUE TITLE
Ne peut plus afficher les paroles

### ISSUE THREAD

**Issue by Bastidn** [thiboot/paillardes-et-chants-public#1]
Bonjour/Bonsoir,

Depuis un petit moment déjà, probablement quelques mois, lorsque je clique sur une paillarde, les paroles ne s'affichent pas et la page charge indéfiniment :

![Screenshot_20210401-225418](https://user-images.githubusercontent.com/18116834/113353174-9363a000-933d-11eb-83c1-c82a5537f945.jpg)

Merci d'avance !

**Comment by thibautLedz** [comment]
Hello !
Ouaip le backend est tombé. Je vais essayer de prendre un peu de temps pour
corriger cela bientôt 😊

**Comment by Pao2S** [comment]
Bonsoir, des nouvelles de ce bug ?

**Comment by Bastidn** [comment]
> Bonsoir, des nouvelles de ce bug ?

Bonsoir, rien n'a changé de mon côté, les bugs sont toujours présents.

**Comment by alanlecart** [comment]
Pareil, en espérant que la checklist revienne pour les congrès de cet été 😁

**Comment by thibautLedz** [comment]
J'ai remis le backend sur pieds ya quelques mois je ferme :-)
